name: Generate
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  generate:
    name: Generate
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Generate
        run: node index.js
      - name: Update
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          branch: main
          skip_checkout: true
          skip_dirty_check: true
          push_options: '--force'
          file_pattern: 'response.json'